version: '3.9'
services:
    uptime-kuma:
        image: louislam/uptime-kuma:1.14.0-alpine
        container_name: uptime-kuma
        restart: unless-stopped
        volumes:
            - ./uptime-kuma:/app/data
        labels:
            # Services
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            # Webinterface HTTP (to HTTPS redirect)
            - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.example.com`)"
            - "traefik.http.routers.uptime-kuma.entrypoints=http"
            - "traefik.http.routers.uptime-kuma.middlewares=http-to-https@file"
            # Webinterface HTTPS
            - "traefik.http.routers.uptime-kuma-ssl.rule=Host(`uptime.example.com`)"
            - "traefik.http.routers.uptime-kuma-ssl.entrypoints=https"
            - "traefik.http.routers.uptime-kuma-ssl.tls=true"
        networks:
            - proxy
networks:
    proxy:
        external: true
