#########################################################################
# Uncomment this section after you have uploaded your own certificates. #
#########################################################################
# tls:
#     certificates:
#         - certFile: /certs/example.com.crt
#           keyFile: /certs/example.com.key
#         - certFile: /certs/mydomain.net.crt
#           keyFile: /certs/mydomain.net.key

http:
    middlewares:
        auth:
            basicAuth:
                users:
                    - "proxy:$apr1$jmf4xbk2$fM1oNaZtJUfJtacCQSoIm0"
        http-to-https:
            redirectscheme:
                scheme: https
                permanent: true
